{
  "$schema" = "https://zed.dev/schema/themes/v0.2.0.json";
  name = "IR Black";
  author = "Todd Werth";
  themes = [{
    name = "IR Black";
    appearance = "dark";
    style = {
      background = "#000000ff";
      "editor.background" = "#000000ff";
      "editor.foreground" = "#f6f3e8ff";
      "editor.gutter.background" = "#000000ff";
      "editor.line_number" = "#7c7c7cff";
      "editor.active_line_number" = "#f6f3e8ff";
      "editor.active_line.background" = "#1a1a1aff";
      "editor.wrap_guide" = "#2a2a2aff";
      "editor.indent_guide" = "#2a2a2aff";
      "editor.indent_guide_active" = "#4e4e4eff";
      border = "#333333ff";
      "border.variant" = "#222222ff";
      "border.focused" = "#96cbfeff";
      "border.selected" = "#96cbfeff";
      "border.transparent" = "#00000000";
      "border.disabled" = "#333333ff";
      "elevated_surface.background" = "#1a1a1aff";
      "surface.background" = "#111111ff";
      "element.background" = "#1a1a1aff";
      "element.hover" = "#2a2a2aff";
      "element.active" = "#333333ff";
      "element.selected" = "#333333ff";
      "element.disabled" = "#1a1a1aff";
      "ghost_element.background" = "#00000000";
      "ghost_element.hover" = "#2a2a2aff";
      "ghost_element.active" = "#333333ff";
      "ghost_element.selected" = "#333333ff";
      "ghost_element.disabled" = "#1a1a1aff";
      text = "#f6f3e8ff";
      "text.muted" = "#7c7c7cff";
      "text.placeholder" = "#4e4e4eff";
      "text.disabled" = "#4e4e4eff";
      "text.accent" = "#96cbfeff";
      icon = "#f6f3e8ff";
      "icon.muted" = "#7c7c7cff";
      "icon.disabled" = "#4e4e4eff";
      "icon.placeholder" = "#4e4e4eff";
      "icon.accent" = "#96cbfeff";
      "status_bar.background" = "#0a0a0aff";
      "title_bar.background" = "#0a0a0aff";
      "title_bar.inactive_background" = "#050505ff";
      "toolbar.background" = "#000000ff";
      "tab_bar.background" = "#0a0a0aff";
      "tab.active_background" = "#1a1a1aff";
      "tab.inactive_background" = "#0a0a0aff";
      "search.match_background" = "#ffffb640";
      "panel.background" = "#0a0a0aff";
      "panel.focused_border" = "#96cbfeff";
      "pane.focused_border" = "#96cbfeff";
      "scrollbar.thumb.background" = "#333333aa";
      "scrollbar.thumb.hover_background" = "#555555aa";
      "scrollbar.thumb.border" = "#00000000";
      "scrollbar.track.background" = "#00000000";
      "scrollbar.track.border" = "#00000000";
      "link_text.hover" = "#96cbfeff";
      conflict = "#ff6c60ff";
      "conflict.background" = "#ff6c6020";
      "conflict.border" = "#ff6c60ff";
      created = "#a8ff60ff";
      "created.background" = "#a8ff6020";
      "created.border" = "#a8ff60ff";
      deleted = "#ff6c60ff";
      "deleted.background" = "#ff6c6020";
      "deleted.border" = "#ff6c60ff";
      error = "#ff6c60ff";
      "error.background" = "#ff6c6020";
      "error.border" = "#ff6c60ff";
      hidden = "#4e4e4eff";
      "hidden.background" = "#0a0a0aff";
      "hidden.border" = "#333333ff";
      hint = "#7c7c7cff";
      "hint.background" = "#0a0a0aff";
      "hint.border" = "#333333ff";
      ignored = "#4e4e4eff";
      "ignored.background" = "#0a0a0aff";
      "ignored.border" = "#333333ff";
      info = "#96cbfeff";
      "info.background" = "#96cbfe20";
      "info.border" = "#96cbfeff";
      modified = "#ffffb6ff";
      "modified.background" = "#ffffb620";
      "modified.border" = "#ffffb6ff";
      predictive = "#4e4e4eff";
      "predictive.background" = "#0a0a0aff";
      "predictive.border" = "#333333ff";
      renamed = "#96cbfeff";
      "renamed.background" = "#96cbfe20";
      "renamed.border" = "#96cbfeff";
      success = "#a8ff60ff";
      "success.background" = "#a8ff6020";
      "success.border" = "#a8ff60ff";
      unreachable = "#4e4e4eff";
      "unreachable.background" = "#0a0a0aff";
      "unreachable.border" = "#333333ff";
      warning = "#ffffb6ff";
      "warning.background" = "#ffffb620";
      "warning.border" = "#ffffb6ff";
      "terminal.background" = "#000000ff";
      "terminal.foreground" = "#f6f3e8ff";
      "terminal.bright_foreground" = "#ffffffff";
      "terminal.dim_foreground" = "#7c7c7cff";
      "terminal.ansi.black" = "#4e4e4eff";
      "terminal.ansi.red" = "#ff6c60ff";
      "terminal.ansi.green" = "#a8ff60ff";
      "terminal.ansi.yellow" = "#ffffb6ff";
      "terminal.ansi.blue" = "#96cbfeff";
      "terminal.ansi.magenta" = "#ff73fdff";
      "terminal.ansi.cyan" = "#c6c5feff";
      "terminal.ansi.white" = "#eeeeeeff";
      "terminal.ansi.bright_black" = "#7c7c7cff";
      "terminal.ansi.bright_red" = "#ffb6b0ff";
      "terminal.ansi.bright_green" = "#ceffabff";
      "terminal.ansi.bright_yellow" = "#ffffcbff";
      "terminal.ansi.bright_blue" = "#b5dcfeff";
      "terminal.ansi.bright_magenta" = "#ff9cfeff";
      "terminal.ansi.bright_cyan" = "#dfdffeff";
      "terminal.ansi.bright_white" = "#ffffffff";
      players = [
        { cursor = "#f6f3e8ff"; background = "#96cbfeff"; selection = "#96cbfe40"; }
        { cursor = "#a8ff60ff"; background = "#a8ff60ff"; selection = "#a8ff6040"; }
        { cursor = "#ff73fdff"; background = "#ff73fdff"; selection = "#ff73fd40"; }
        { cursor = "#ffffb6ff"; background = "#ffffb6ff"; selection = "#ffffb640"; }
      ];
      syntax = {
        comment  = { color = "#7c7c7cff"; font_style = "italic"; };
        string   = { color = "#a8ff60ff"; };
        number   = { color = "#ff73fdff"; };
        keyword  = { color = "#96cbfeff"; };
        function = { color = "#ffffb6ff"; };
        type     = { color = "#ffffb6ff"; };
        variable = { color = "#f6f3e8ff"; };
        constant = { color = "#ff6c60ff"; };
        operator = { color = "#f6f3e8ff"; };
        property = { color = "#c6c5feff"; };
        attribute = { color = "#96cbfeff"; };
        tag      = { color = "#96cbfeff"; };
        label    = { color = "#ffffb6ff"; };
        punctuation = { color = "#f6f3e8ff"; };
        "punctuation.bracket" = { color = "#f6f3e8ff"; };
        "punctuation.delimiter" = { color = "#f6f3e8ff"; };
        "punctuation.special" = { color = "#ff73fdff"; };
        "string.escape" = { color = "#ff73fdff"; };
        "string.special" = { color = "#ff73fdff"; };
        "string.regex" = { color = "#ff73fdff"; };
        "variable.special" = { color = "#ff6c60ff"; };
        "keyword.operator" = { color = "#f6f3e8ff"; };
        boolean = { color = "#ff6c60ff"; };
        "comment.doc" = { color = "#7c7c7cff"; font_style = "italic"; };
        emphasis = { font_style = "italic"; };
        "emphasis.strong" = { font_weight = 700; };
        title = { color = "#ffffb6ff"; font_weight = 700; };
        link_text = { color = "#96cbfeff"; };
        link_uri = { color = "#a8ff60ff"; };
      };
    };
  }];
}
